[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501

[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = true

[theme]
base = "light"
primaryColor = "#FE6565"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#EAF4FA"
textColor = "#006FB3"
font = "sans serif"
