[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501

[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = true

[theme]
base = "light"
primaryColor = "#D52B1E"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#EAF2FB"
textColor = "#003DA5"
font = "sans serif"
